### ISSUE TITLE
selected-fc-port must be a reference

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/core#28]
This issue was found during the discussions of the SyncProtectionSpec ([Sync #45](https://github.com/openBackhaul/synchronization/issues/45))

The UML Object Class "FcSwitch" (yang grouping fc-switch) contains an attribute "selectedFcPort". 

Currently the UML2YANG tool generates the following output:

```
    list selected-fc-port {
      key "local-id";
      uses fc-port;
      description
        "Indicates which points are selected by the switch.
         Depending on the switch spec (via FcSpec)
         - more than one FcPort can be selected at any one time (e.g. egress switch, ingress packet switch)
         - zero FcPorts can be selected. For an ingress switch this indicates that the switch common (egress) is 'high impedance'.";
    }
```

However, the following output is expected:
The selected-fc-port is a reference to an FC port of within THIS FC.

```
    leaf-list selected-fc-port {
      type union {
        type leafref {
          path "/core-model:control-construct/core-model:forwarding-domain/core-model:fc[uuid = current()/../../uuid]/fc-port/local-id";
          require-instance false;
        }
        type leafref {
          path "/core-model:control-construct/core-model:forwarding-domain/core-model:fc[uuid = current()/../../../uuid]/fc-port/local-id";
          require-instance false;
        }
      }
      description
        "Indicates which points are selected by the switch.
         Depending on the switch spec (via FcSpec)
         - more than one FcPort can be selected at any one time (e.g. egress switch, ingress packet switch)
         - zero FcPorts can be selected. For an ingress switch this indicates that the switch common (egress) is 'high impedance'.";
    }
```

It is assumed that the "pruning and refactoring" step will correct the CoreModel.uml so that the UML2 YANG does not change.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 7th of September 2022:**
The current FcSwitch :: selectedFcPort : FcPort attribute in the Core modelling acts like a composite association.
Means, the selected FcPorts are part of the FcSwitch.
This is not reasonable, because FcPorts must be part of the FC, and the selectedFcPort attribute at the FcSwitch must reference an already existing FcPort. 

Another problem is that FcPorts occur at two different places in the Core modeling, which would require a union to facilitate referencing FcPorts at two different locations (FcSwitch and ConfigurationAndSwitchControl).
Instead of using the union, deleting one of the locations from the modeling is proposed.
Because it seems very unlikely that we would ever define several switching rules for a single FC, we are proposing to prune the ConfigurationAndSwitchControl class from the modeling instead.

**Details:**
- The Core Model must be altered during the pruning and refactoring, but before generating the YANG, in such a way that the selectedFcPort attribute gets translated as a reference (shared association) instead of a list (composite association).
- The ConfigurationAndSwitchControl class shall be pruned from the Core modelling during the pruning and refactoring step for individualizing the Core Model.
- The SyncProtectionSpec shall augment the Fc :: FcSwitch :: ControlParameters class instead of the Fc :: FcSwitch :: _ConfigurationAndSwitchControl_ :: ControlParameters class ([corresponding issue in the Synchronization Repository](https://github.com/openBackhaul/synchronization/issues/47)).

**Comment by openBackhaul** [comment]
Implemented as decided.
